config/routes.rb
Rails.application.routes.draw do
  resources :projects
  #get 'page/home'

  # Important: set Devise for the users resource before delcaring
  #   any further user resources
  devise_for :users, controllers: { sessions: 'session/sessions' }

  resources :users do
    collection do
      get 'search'
    end
  end

  root 'page#home'

end

app/models/concerns/project_helper.rb
require 'active_support/concern'

module ProjectHelper extend ActiveSupport::Concern
    include MarkdownHelper
    
    class NoAttributeError < RuntimeError
    end
    
    def method_missing(method_name, *args, &block)
       # cast the method to a string here so that we are not casting it all over the place
       m_name = method_name.to_s
       split_name = m_name.split('_')
       
       if split_name.last == 'markdown'
           return attribute_markdown m_name
       end
       
       raise NoMethodError.new("undefined method `#{ method_name }` for #{ self }")
    end
    
    private 
    
    def attribute_markdown m_name
        # Get the attribute that we want to update
        # => eg: `big_string_markdown` becomes `big_string`
        attribute = m_name[0, m_name.rindex('_')]
           
        if self.has_attribute? attribute
            to_markdown = self.attributes[attribute]
            return markdown(to_markdown.nil? ? '' : to_markdown)
        else
            raise NoAttributeError.new("no attribute named `#{ attribute }` for #{ self }")
        end
    end
end

app/models/project.rb
class Project < ApplicationRecord
    include ProjectHelper
    
    before_create :create_as_active, :create_as_auto_start_iter_off
    
    belongs_to :created_by, class_name: 'User', foreign_key: 'created_by_id'
    belongs_to :owned_by, class_name: 'User', foreign_key: 'owned_by_id'
    
    enum status: { active: 0, archived: 1 }
    enum auto_start_iter: { off: 0, on: 1 }
    
    validates_presence_of :name
    validates :name, uniqueness: true
    
    validates_presence_of :description
    
    def as_json option={}
       {
           id: id,
           name: name,
           status: status,
           description: description,
           profile: profile,
           profile_markdown: profile_markdown,
           auto_start_iter: auto_start_iter,
           iter_length: iter_length
       } 
    end
    
    private
    
    def create_as_active
       self.status = 0 
    end
    
    def create_as_auto_start_iter_off
       self.auto_start_iter = 0 
    end
    
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    
    if params[:status].blank? || params[:status] == 'active'
      @projects = Project.active.page(params[:page]).per(10)
    elsif params[:status] == 'archived'
      @projects = Project.archived.page(params[:page]).per(10)
    end
    
  end

  def show
  end

  def new
    @project = Project.new
    
    toReturn = ( render_to_string :partial => "modal_new", :layout => false, :locals => {:project => @project})
    respond_to do |format|
      format.json { render :layout => false, :json => {:html => toReturn }  } #:json => {:html => toReturn }
    end
  end

  def edit
    begin
      authorize @project
    rescue Pundit::NotAuthorizedError
      redirect_to @project
    end
  end

  def create
    @project = Project.new(project_params)
    @project.created_by = current_user

    respond_to do |format|
      if @project.save
        format.json { render :layout => false, :json => { :location => edit_project_path(@project) }}
        format.html { redirect_to edit_project_path(@project), notice: 'Project was successfully created.' }
      else
        format.json { render json: @project.errors.full_messages.to_json, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        #format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render json: @project, status: :ok}
      else
        #format.html { render :edit }
        format.json { render json: @project.errors.full_messages.to_json, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if project_params[:name] == @project.name
      @project.destroy
      redirect_to projects_path, notice: 'Project was successfully destroyed.' 
    elsif project_params[:name].blank?
      respond_to do |format|
        format.json { render json: 'You must enter the name to delete this project', status: :unprocessable_entity }
      end  
    else
      respond_to do |format|
        format.json { render json: 'Incorrect name', status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(
        :name, :description, :status, 
        :owned_by_id, :profile, :auto_start_iter,
        :iter_length )
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, class: 'inline-form') do |f| %>

  <div class='form-group'>
    <%= inline_switch(f, :status, project.status, Project.statuses) %>
  </div>

  <div class='form-group'>
    <%= inline_update_text_field(f, :name, project.name) %>
  </div>
  
  <div class='form-group'>
    <%= inline_update_text_field(f, :description, project.description) %>
  </div>

  <div class='form-group'>
      <%= inline_update_select2(f, :owned_by, 
                    'Select a user', 
                    search_users_path, 
                    'email') do  %>
        <% if !project.owned_by.nil? %>
          <option value="<%= project.owned_by.id %>">
            <%= project.owned_by.name %>
          </option>
        <% end %>
      <% end %>
  </div>
  
  <hr/>
  
  <div class='form-group'>
    <%= inline_switch(f, :auto_start_iter, project.auto_start_iter, Project.auto_start_iters) %>
  </div>
  
  <div class='form-group'> 
    <%= inline_dropdown(f, :iter_length, project.iter_length, (1..4).collect{ |x| [ "#{x} weeks", x]   } ) %>
  </div>
  
  <hr/>
  
  <div class='form-group'>
    <%= inline_markdown(f, :profile, project.profile_markdown)   %>
  </div>
  
<% end %>

app/views/projects/_modal_new.html.erb
<div class='modal-header'>
  <h2>Create new project</h2>
</div>
<div class='modal-body'>
  <%= render partial: 'shared/modal_error_block' %>
  
  <%= form_with(model: project, id: 'create-modal') do |f| %>

    <div class='form-group'>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class='form-group'>
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control', rows: 5 %>
    </div>

  <% end %>
  
</div>
<div class='modal-footer'>
  <div id="actions">
    <button id='modal-create' class='btn btn-primary raised'>Create</button>
    <button id='modal-close' class='btn btn-danger raised' data-dismiss='modal'>Close</button>
  </div>        
</div>

app/views/projects/edit.html.erb
 <div class="widget-box">
    <div class="widget-title">
        <span class="icon">
            <%= fa_icon 'eye' %>
        </span>
        <h5>Project:</h5>
        <h5 id='project-name'><%= @project.name %></h5>
    </div>
    <div class="widget-content">
        <div class='row'>
            <div class='col-md-3'>
                <label>Created by:</label>
            </div>
            <div class='col-md-9'>
                <span><%= @project.created_by.name %></span>
            </div>
        </div>
        <div class="row-fluid">
            <%= render 'form', project: @project %>
        </div>
        <div id='delete-section'>
    <button id='destroy-project'>Delete</button> 
    
    <div id='delete-warning' style='display:none'>
        
        <p id="notice"></p>
        
        <%= form_with(model: @project, method: 'delete', id:'delete-project-form') do |f| %>
            <input id="project_name" name="project[name]" type="text" />
            <%= f.submit 'Confirm', id: 'delete-project' %>
        <% end %>
    </div>
</div>

    </div>
</div>


<script type='text/javascript'>
    $(function(){
        $('body').on('click', '#destroy-project', function() {
            $('#delete-warning').show();
        });
        
        $('body').on('ajax:error', '#delete-project-form', function(event, xhr, status, error) {
           $('#notice').html(xhr.responseText)
        });
        
        $('#project[name]').on('keyup change', function() {
            console.log('here')
            $('#project-name').html( $(this).val() )
        });
        
    })
</script>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<% if admin? %>
  <div class='row'>
    <div class='col-md-1'>
      <button id='bobo' type='button' class='btn btn-primary raised' 
        data-toggle='modal'  data-target='#create-modal'
        data-url="<%= new_project_path %>" 
        data-method="GET">Create</button>
    </div>
  </div>
<% end %>

<div class='widget-box'>
  <div class='widget-title'>
    <h5>Projects</h5>
    <div class='widget-content nopadding'>
      <div class='dataTables_wrapper' role='grid'>
        <div>
          <div class='dataTables_length'>
            <label>
              Status
              <select id='project-status'>
                <option value='active'>Active</option>
                <option value='archived'>Archived</option>
              </select>
            </label>
          </div>
        </div>
        
        <table class='table table-bordered data-table dataTable'>
          <thead>
            <tr role='row'>
              <th class='ui-state-default'>
                <div class='DataTables_sort_wrapper'>
                  Name
                </div>
              </th>
              <th class='ui-state-default'>
                <div class='DataTables_sort_wrapper'>
                  Description
                </div>
              </th>
              <th class='ui-state-default'>
                <div class='DataTables_sort_wrapper'>
                  Owner
                </div>
              </th>
            </tr>
          </thead>

          <tbody role='alert'>
            <% @projects.each do |project| %>
              <tr>
                <td><%= link_to project.name, edit_project_path(project) %></td>
                <td><%= project.description %></td>
                <td><%= project.owned_by.name unless project.owned_by.nil? %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class='fg-toolbar ui-toolbar ui-widget-header ui-corner-bl ui-corner-br ui-helper-clearfix'>
          <div class='dataTables_paginate fg-buttonset ui-buttonset fg-buttonset-multi ui-buttonset-multi paging_full_numbers'>
            <%= paginate @projects, params: { status: params[:status] } %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<br>

<%= render partial: 'shared/modal_base' %>

<script type='text/javascript'>
  $(function() {
    var status = getUrlVars()['status']
    
    if(status)
    $('#project-status').val(status)
    
    $('body').on('change', '#project-status', function(event) {
      window.location = '<%= projects_path %>/?status=' + this.value
    });
  })
  
function getUrlVars() {
    var vars = [], hash;
    var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
    for(var i = 0; i < hashes.length; i++) {
        hash = hashes[i].split('=');
        vars.push(hash[0]);
        vars[hash[0]] = hash[1];
    }
    return vars;
}
</script>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
 <div class="widget-box">
    <div class="widget-title">
        <span class="icon">
            <%= fa_icon 'info' %>
        </span>
        <h5><%= @project.name %></h5>
    </div>
    <div class="widget-content">
        <div class="row-fluid">
            <%= @project.profile_markdown %>
        </div>
    </div>
</div>